import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import vm from 'node:vm';

const sandbox = {};
vm.createContext(sandbox);
const gameSource = readFileSync(new URL('./game.mjs', import.meta.url), 'utf8');
const indexSource = readFileSync(new URL('./index.html', import.meta.url), 'utf8');
vm.runInContext(gameSource, sandbox);
const { chooseUnique, clamp, joystickVector, enemyStats, enemyScore, XP_PER_GEM, VAMPIRE_HEAL_PER_HIT, VAMPIRE_RUNE_CHANCE, RUNE_CONFIG, RUNE_KINDS, rollRune, runeMaxFor, LEADERBOARD_LIMIT, normalizePlayerName, readLeaderboard, saveLeaderboardEntry, BIOME_DURATION, BOSS_TIME, BIOMES, OBSTACLE_ART, RELIC_ART, ENEMY_ART, ENEMY_SPRITE_FRAMES, EFFECT_ART, BOSS_SHOT_ART, HURRICANE_SPEED, HURRICANE_KNOCKBACK, hurricaneKnockback, healOnLevel, growPlayerStatsOnLevel, endlessMultiplier, tuneBossStats, hitFeedbackAlpha, relicSpawnMinDistance, FAN_HANDLE_ANGLE, ACTIVE_SKILLS, ACTIVE_SKILL_MAX_LEVEL, skillMaxLevel, RELIC_BUILDING_SITES, RELIC_RESPAWN_INTERVAL, RELIC_MAX_ACTIVE, MUSIC_LOOP_SECONDS, MUSIC_GAIN, MUSIC_STAGES, UPGRADES, PICKUPS, makeRelicBuilding, makeRelicBuildings, activeSkillCooldown, createMusicLoop, enemyVisualScale, getBiomeIndex, cameraFromPlayer, directionFrame, mirrorFacing, orbitFanAngle, pickupIndex, tileRange, obstacleAt, hitsObstacle, facingAngle, fanAngles, applyPickup, applyVampireHeal, difficultyFor, musicFrequency, musicStageFor, bossBarVisible, bossBarLayout, bossArrowLayout, bossShotArt, spawnInterval, bossSpawnInterval, endlessSpawnCount, nextExperienceTarget, growthForm, stageClock, nextBiomeAfterBoss, wrapCanvasText } = sandbox.__civilizationTest;

assert.equal(clamp(12, 0, 10), 10);
assert.equal(joystickVector(0, 0).x, 0);
assert.equal(joystickVector(0, 0).y, 0);
assert.equal(joystickVector(100, 0).x, 1);
assert.equal(joystickVector(100, 0).y, 0);
const diagonalJoystick = joystickVector(100, 100);
assert.ok(Math.abs(Math.hypot(diagonalJoystick.x, diagonalJoystick.y) - 1) < 0.000001);
assert.equal(gameSource.includes('setPointerCapture'), false);
assert.ok(gameSource.includes('this.preloadStage(0)'));
assert.ok(gameSource.includes('void this.preloadStage(1)'));
assert.equal(gameSource.includes('if (!this.initialAssetsReady) return;'), false);
assert.ok(gameSource.includes("evolution-guide.webp"));
assert.ok(gameSource.includes('enterEndlessMode'));
assert.equal(gameSource.includes('this.finish(true)'), false);
assert.ok(gameSource.includes('registerBossDefeat'));
assert.ok(gameSource.includes('requestFullscreen'));
assert.equal(indexSource.includes('id="rotate-screen"'), false);
assert.ok(indexSource.includes('rel="preload" as="image"'));
assert.ok(indexSource.includes('boss-tide-crab.webp?v=20260828-1'));
assert.equal(indexSource.includes('data-difficulty="normal" disabled'), false);
assert.ok(gameSource.includes('Math.ceil(p.hp)'));
const textCtx = { measureText: value => ({ width: [...value].length }) };
assert.deepEqual(Array.from(wrapCanvasText(textCtx, '吸血符文 +1 · 命中回复 0.2 点', 12)), ['吸血符文 +1 · 命中', '回复 0.2 点']);
assert.equal(gameSource.includes('for (const [kind, art] of Object.entries(ENEMY_ART))'), false);
assert.deepEqual(Array.from(chooseUnique(['a', 'b', 'c'], 3, () => 0)), ['a', 'b', 'c']);
assert.equal(new Set(chooseUnique(['a', 'b', 'c'], 3)).size, 3);
assert.equal(enemyStats('reversionBoss', 1.2).hp, 984);
assert.equal(enemyStats('tideBoss').sprite, 'tideBoss');
assert.equal(enemyStats('tideBoss').shots, 7);
assert.equal(enemyStats('groveBoss').sprite, 'groveBoss');
assert.equal(enemyStats('tideBoss').skill, 'tide');
assert.equal(enemyStats('groveBoss').skill, 'grove');
assert.equal(enemyStats('groveBoss').shots, 5);
assert.deepEqual(Object.keys(BOSS_SHOT_ART).sort(), ['groveBoss', 'reversionBoss', 'tideBoss']);
assert.equal(bossShotArt({ boss: true, kind: 'tideBoss' }).sprite, 'bubble');
assert.equal(bossShotArt({ boss: true, kind: 'groveBoss' }).sprite, 'leaf');
assert.equal(bossShotArt({ boss: true, kind: 'reversionBoss' }).sprite, 'flame');
assert.equal(bossShotArt({ boss: false, kind: 'reversionBoss' }), null);
assert.equal(enemyStats('crab').skill, 'pulse');
assert.equal(enemyStats('wisp').canFly, true);
assert.equal(enemyStats('mutant', 1, 1.3).damage, 20);
assert.equal(enemyStats('leech').enrages, true);
assert.equal(enemyStats('infantry').guardAfterShot, true);
assert.equal(enemyStats('savage').name, '野人');
assert.equal(enemyStats('savage').skill, 'dash');
assert.equal(enemyStats('infantry').name, '中世纪步兵');
assert.equal(enemyStats('infantry').skill, 'throw');
assert.equal(enemyStats('infantry').shotKind, 'spear');
assert.equal(enemyStats('amoeba').shots, 2);
assert.equal(BIOMES[0].enemies.includes('savage'), true);
assert.equal(BIOMES[1].enemies.includes('infantry'), true);
assert.equal(OBSTACLE_ART.shore.source.includes('shore-reef.webp'), true);
assert.equal(OBSTACLE_ART.forest.source.includes('forest-tree.webp'), true);
assert.equal(OBSTACLE_ART.volcano.source.includes('volcano-spire.webp'), true);
assert.deepEqual(Object.keys(RELIC_ART).sort(), ['forest', 'shore', 'volcano']);
for (const art of Object.values(RELIC_ART)) assert.equal(existsSync(new URL(art.source.split('?')[0], import.meta.url)), true);
assert.deepEqual(Object.keys(ENEMY_ART).sort(), ['amoeba', 'beetle', 'crab', 'groveBoss', 'infantry', 'leech', 'moth', 'mutant', 'reclaimer', 'reversionBoss', 'savage', 'thorn', 'tideBoss', 'wisp']);
assert.equal(Object.keys(ENEMY_ART).every(kind => enemyStats(kind).sprite === kind), true);
for (const art of Object.values(ENEMY_ART)) assert.equal(existsSync(new URL(art.source.split('?')[0], import.meta.url)), true);
assert.deepEqual(Object.keys(EFFECT_ART).sort(), ['bubble', 'fan', 'flame', 'hurricane', 'leaf', 'venom']);
for (const art of Object.values(EFFECT_ART)) assert.equal(existsSync(new URL(art.source.split('?')[0], import.meta.url)), true);
assert.equal(HURRICANE_SPEED, 580);
assert.equal(HURRICANE_KNOCKBACK, 42);
const hurricanePush = hurricaneKnockback(3, 4, false);
assert.equal(Math.round(hurricanePush.x * 10), 252);
assert.equal(Math.round(hurricanePush.y * 10), 336);
assert.equal(hurricaneKnockback(3, 4, true), null);
const hurricaneDrawBlock = gameSource.match(/if \(b\.kind === 'hurricane'\) \{([\s\S]*?)continue;/)?.[1];
assert.ok(hurricaneDrawBlock);
assert.equal(hurricaneDrawBlock.includes('ctx.rotate'), false);
const levelHealPlayer = { hp: 45, maxHp: 100 };
healOnLevel(levelHealPlayer);
assert.equal(levelHealPlayer.hp, 95);
healOnLevel(levelHealPlayer);
assert.equal(levelHealPlayer.hp, 100);
assert.equal(ENEMY_ART.savage.source.includes('/savage.webp'), true);
assert.equal(ENEMY_ART.infantry.source.includes('/infantry.webp'), true);
assert.equal(ENEMY_SPRITE_FRAMES.savage.length, 9);
assert.equal(ENEMY_SPRITE_FRAMES.infantry.length, 9);
assert.equal(ENEMY_SPRITE_FRAMES.savage[0].w, 418);
assert.deepEqual(Object.keys(ACTIVE_SKILLS).sort(), ['dash', 'spear', 'ward']);
assert.equal(ACTIVE_SKILLS.dash.key, 'Q');
assert.equal(ACTIVE_SKILLS.spear.label, '飓风');
assert.equal(RELIC_BUILDING_SITES.length, 3);
assert.deepEqual(Array.from(RELIC_BUILDING_SITES, site => site.skill).sort(), ['dash', 'spear', 'ward']);
assert.equal(makeRelicBuildings().every(building => building.isBuilding && building.hp === building.maxHp), true);
assert.equal(makeRelicBuildings('volcano').every(building => building.terrain === 'volcano'), true);
assert.deepEqual({ x: makeRelicBuilding(RELIC_BUILDING_SITES[0], 12, 34).x, y: makeRelicBuilding(RELIC_BUILDING_SITES[0], 12, 34).y }, { x: 12, y: 34 });
assert.ok(RELIC_RESPAWN_INTERVAL <= 8 && RELIC_MAX_ACTIVE >= 9);
assert.equal(ACTIVE_SKILL_MAX_LEVEL, 15);
assert.deepEqual(Object.fromEntries(Object.entries(RUNE_CONFIG).map(([kind, config]) => [kind, config.max])), { vampire: 8, rage: 10, shell: 8, wind: 8, echo: 8 });
assert.equal(skillMaxLevel({ skillCapBonus: 4 }), ACTIVE_SKILL_MAX_LEVEL + 4);
assert.equal(runeMaxFor({ runeCapBonus: 3 }, 'vampire'), RUNE_CONFIG.vampire.max + 3);
assert.ok(relicSpawnMinDistance(844, 390) > Math.hypot(844, 390) / 2);
assert.ok(RELIC_BUILDING_SITES.every(site => Math.hypot(site.x, site.y) > relicSpawnMinDistance(1280, 720, 0)));
const grownPlayer = { maxHp: 100, hp: 40, damage: 18, speed: 170 };
growPlayerStatsOnLevel(grownPlayer, 2);
assert.ok(grownPlayer.maxHp > 100 && grownPlayer.damage > 18 && grownPlayer.speed > 170);
assert.equal(hitFeedbackAlpha(1), .28);
assert.equal(hitFeedbackAlpha(0), 0);
assert.ok(endlessMultiplier(3) > endlessMultiplier(1));
assert.equal(endlessSpawnCount(0), 1);
assert.equal(endlessSpawnCount(4), 3);
assert.ok(spawnInterval(20, difficultyFor('normal'), 2) < spawnInterval(20, difficultyFor('normal'), 0));
assert.ok(bossSpawnInterval(difficultyFor('normal'), 2) < bossSpawnInterval(difficultyFor('normal'), 0));
const tunedBoss = tuneBossStats({ speed: 40, skillEvery: 4, skillRange: 200, skillRadius: 100, shots: 5, shotSpeed: 180 }, 2);
assert.ok(tunedBoss.speed > 40 && tunedBoss.skillEvery < 4 && tunedBoss.skillRange > 200 && tunedBoss.skillRadius > 100 && tunedBoss.shots > 5 && tunedBoss.shotSpeed > 180);
assert.equal(nextExperienceTarget(7), 10);
assert.equal(XP_PER_GEM, 1);
assert.equal(VAMPIRE_HEAL_PER_HIT, .2);
assert.equal(VAMPIRE_RUNE_CHANCE, .02);
assert.deepEqual(Object.keys(RUNE_CONFIG).sort(), ['echo', 'rage', 'shell', 'vampire', 'wind']);
assert.deepEqual(Array.from(RUNE_KINDS).sort(), ['echo', 'rage', 'shell', 'vampire', 'wind']);
assert.equal(rollRune({}, () => .019), 'vampire');
assert.equal(rollRune({}, () => .021), 'rage');
assert.equal(rollRune({ vampireLevel: RUNE_CONFIG.vampire.max }, () => .001), 'rage');
const vampirePlayer = { hp: 50, maxHp: 100, vampireLevel: 0 };
applyPickup(vampirePlayer, 'vampire');
applyPickup(vampirePlayer, 'vampire');
assert.equal(vampirePlayer.vampireLevel, 2);
assert.ok(Math.abs(applyVampireHeal(vampirePlayer, vampirePlayer.vampireLevel) - .4) < .000001);
assert.ok(Math.abs(vampirePlayer.hp - 50.4) < .000001);
const runePlayer = { hp: 100, maxHp: 100, rageRune: 0, shellRune: 0, windRune: 0, echoRune: 0 };
applyPickup(runePlayer, 'rage');
applyPickup(runePlayer, 'shell');
applyPickup(runePlayer, 'wind');
applyPickup(runePlayer, 'echo');
assert.deepEqual({ rage: runePlayer.rageRune, shell: runePlayer.shellRune, wind: runePlayer.windRune, echo: runePlayer.echoRune }, { rage: 1, shell: 1, wind: 1, echo: 1 });
assert.equal(enemyScore(enemyStats('mutant'), difficultyFor('normal')), 36);
assert.ok(enemyScore(enemyStats('mutant'), difficultyFor('harsh')) > enemyScore(enemyStats('mutant'), difficultyFor('gentle')));
assert.equal(LEADERBOARD_LIMIT, 20);
assert.equal(normalizePlayerName('  测试玩家　　　　　　　　　'), '测试玩家');
const fakeStorage = { data: new Map(), getItem(key) { return this.data.get(key) || null; }, setItem(key, value) { this.data.set(key, value); } };
saveLeaderboardEntry('低分', 12, '中', 30, fakeStorage);
saveLeaderboardEntry('高分', 90, '难', 50, fakeStorage);
const leaderboard = readLeaderboard(fakeStorage);
assert.equal(leaderboard[0].name, '高分');
assert.equal(leaderboard[1].score, 12);
assert.ok(activeSkillCooldown({ dashLevel: 1 }, 'dash') < ACTIVE_SKILLS.dash.cooldown);
assert.ok(activeSkillCooldown({ wardLevel: 1 }, 'ward') < ACTIVE_SKILLS.ward.cooldown);
assert.ok(activeSkillCooldown({ dashLevel: ACTIVE_SKILL_MAX_LEVEL }, 'dash') < activeSkillCooldown({ dashLevel: 1 }, 'dash'));
assert.ok(activeSkillCooldown({ spearLevel: ACTIVE_SKILL_MAX_LEVEL }, 'spear') < activeSkillCooldown({ spearLevel: 1 }, 'spear'));
assert.ok(activeSkillCooldown({ wardLevel: ACTIVE_SKILL_MAX_LEVEL }, 'ward') < activeSkillCooldown({ wardLevel: 1 }, 'ward'));
assert.ok(activeSkillCooldown({ dashLevel: 1, echoRune: 3 }, 'dash') < activeSkillCooldown({ dashLevel: 1 }, 'dash'));
assert.equal(mirrorFacing(3), true);
assert.equal(mirrorFacing(5), false);
assert.ok(Math.abs(orbitFanAngle(0) + FAN_HANDLE_ANGLE - Math.PI) < .000001);
assert.ok(enemyVisualScale({ xp: 18, boss: true }, ENEMY_ART.reversionBoss) > enemyVisualScale({ xp: 1, boss: false }, ENEMY_ART.amoeba));
assert.ok(enemyVisualScale({ xp: 18, boss: true }, ENEMY_ART.reversionBoss) > enemyVisualScale({ xp: 14, boss: true }, ENEMY_ART.tideBoss));
assert.equal(UPGRADES.some(upgrade => upgrade.id === 'chain'), true);
assert.equal(UPGRADES.some(upgrade => upgrade.id === 'wheel'), true);
const orbitUpgrade = UPGRADES.find(upgrade => upgrade.id === 'orbit');
const orbitPlayer = { orbitCount: 1, orbitDamage: 14, orbitEvery: .36 };
orbitUpgrade.apply(orbitPlayer);
assert.deepEqual({ count: orbitPlayer.orbitCount, damage: orbitPlayer.orbitDamage, every: Math.round(orbitPlayer.orbitEvery * 100) }, { count: 3, damage: 22, every: 30 });
assert.deepEqual(Object.keys(PICKUPS).sort(), ['bone', 'echo', 'ember', 'fruit', 'haste', 'rage', 'relic', 'shell', 'vampire', 'ward', 'wind']);
const camera = cameraFromPlayer({ x: 900, y: -120 }, 390, 844);
assert.equal(camera.x, 705);
assert.equal(camera.y, -542);
assert.equal(BIOME_DURATION, 40);
assert.equal(BOSS_TIME, 40);
assert.deepEqual([getBiomeIndex(0), getBiomeIndex(40), getBiomeIndex(160)], [0, 1, 2]);
assert.deepEqual(Array.from(BIOMES, biome => biome.boss), ['tideBoss', 'groveBoss', 'reversionBoss']);
assert.equal(stageClock(BOSS_TIME, true, 60), BOSS_TIME);
assert.equal(stageClock(BOSS_TIME, false, 1), BOSS_TIME + 1);
assert.deepEqual([nextBiomeAfterBoss(0), nextBiomeAfterBoss(1), nextBiomeAfterBoss(2)], [1, 2, null]);
assert.equal(MUSIC_STAGES.length, 9);
assert.deepEqual([musicStageFor(0), musicStageFor(2), musicStageFor(0, { boss: true, biomeIndex: 0 }), musicStageFor(1, { boss: true, biomeIndex: 1 }), musicStageFor(2, { boss: true, biomeIndex: 2 }), musicStageFor(1, { boss: true, biomeIndex: 1, phaseTwo: true })], [0, 2, 3, 4, 5, 7]);
assert.equal(bossBarVisible({ boss: true, hp: 12, maxHp: 20 }), true);
assert.equal(bossBarVisible({ boss: true, hp: 0, maxHp: 20 }), false);
assert.equal(bossBarVisible({ boss: true, hp: 12, maxHp: 20, dead: true }), false);
const bossLayout = bossBarLayout(360, 640);
assert.equal(bossLayout.x, 27);
assert.equal(bossLayout.y, 109);
assert.equal(bossLayout.width, 306);
const bossArrow = bossArrowLayout(360, 640, { boss: true, x: 1000, y: 0, hp: 20, maxHp: 20 }, { x: 0, y: 0 });
assert.ok(bossArrow && bossArrow.offscreen && bossArrow.x >= 26 && bossArrow.x <= 334 && bossArrow.y >= 150 && bossArrow.y <= 612);
assert.equal(bossArrowLayout(360, 640, { boss: true, x: 1000, y: 0, hp: 0, maxHp: 20 }), null);
assert.deepEqual([-1, 0, 1, 0].map((x, index) => directionFrame(x, [0, -1, 0, 1][index])), [3, 1, 5, 7]);
assert.deepEqual([directionFrame(-1, -1), directionFrame(1, -1), directionFrame(-1, 1), directionFrame(1, 1)], [0, 2, 6, 8]);
assert.equal(tileRange(-.000001, 360, 112).start, -2);
assert.equal(tileRange(-.000001, 360, 112).end, 4);
let generatedObstacle;
for (let y = -5; y <= 5 && !generatedObstacle; y += 1) {
  for (let x = -5; x <= 5 && !generatedObstacle; x += 1) generatedObstacle = obstacleAt(x, y);
}
assert.ok(generatedObstacle);
assert.equal(hitsObstacle(generatedObstacle.x, generatedObstacle.y, 1), true);
assert.equal(hitsObstacle(0, 0, 1), false);
assert.equal(facingAngle(5), 0);
assert.deepEqual(Array.from(fanAngles(0, 3, .23)).map(value => Math.round(value * 100) / 100), [-.23, 0, .23]);
assert.equal(difficultyFor('unknown').label, difficultyFor('normal').label);
assert.ok(difficultyFor('harsh').hp > difficultyFor('normal').hp);
assert.ok(difficultyFor('harsh').speed > difficultyFor('normal').speed);
assert.ok(difficultyFor('normal').speed > difficultyFor('gentle').speed);
assert.ok(spawnInterval(0, difficultyFor('harsh')) < spawnInterval(0, difficultyFor('normal')));
assert.ok(spawnInterval(0, difficultyFor('normal')) < .8);
assert.deepEqual([pickupIndex(4, 4, 6), pickupIndex(5, 5, 6), pickupIndex(12, 6, 6)], [0, 0, 1]);
assert.equal(growthForm(-1).kind, 'gene');
assert.equal(growthForm(1).kind, 'flint');
assert.equal(growthForm(8).kind, 'ember');
const pickupPlayer = { hp: 88, maxHp: 100, nova: 4, pierce: 0 };
applyPickup(pickupPlayer, 'fruit');
applyPickup(pickupPlayer, 'ember');
applyPickup(pickupPlayer, 'bone');
assert.deepEqual(pickupPlayer, { hp: 100, maxHp: 100, nova: 0, pierce: 1 });
const bonusPickupPlayer = { hp: 100, maxHp: 100, nova: 0, pierce: 0, haste: 0, invuln: 0 };
assert.equal(applyPickup(bonusPickupPlayer, 'relic').vacuum, true);
applyPickup(bonusPickupPlayer, 'haste');
applyPickup(bonusPickupPlayer, 'ward');
assert.deepEqual(bonusPickupPlayer, { hp: 100, maxHp: 100, nova: 0, pierce: 0, haste: 8, invuln: 3 });
assert.equal(musicFrequency(0), 110);
assert.ok(MUSIC_GAIN >= 1.10);
assert.ok(MUSIC_STAGES[0].energy < MUSIC_STAGES[5].energy);
const fakeAudioContext = {
  sampleRate: 100,
  createBuffer(_channels, length, sampleRate) {
    const data = new Float32Array(length);
    return { length, duration: length / sampleRate, data, getChannelData: () => data };
  },
};
const musicLoop = createMusicLoop(fakeAudioContext);
assert.equal(musicLoop.length, MUSIC_LOOP_SECONDS * fakeAudioContext.sampleRate);
assert.ok(Array.from(musicLoop.data).every(Number.isFinite));
assert.ok(Math.abs(musicLoop.data[0] - musicLoop.data.at(-1)) < .02);
const bossMusicLoop = createMusicLoop(fakeAudioContext, 3);
assert.equal(bossMusicLoop.length, musicLoop.length);
assert.ok(bossMusicLoop.data.some((sample, index) => Math.abs(sample - musicLoop.data[index]) > .0001));
assert.ok(Math.abs(bossMusicLoop.data[0] - bossMusicLoop.data.at(-1)) < .02);
console.log('game model checks passed');
